// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Answer struct {
	Uid           pgtype.UUID      `json:"uid"`
	Content       string           `json:"content"`
	QuestionUid   pgtype.UUID      `json:"question_uid"`
	TimeCreated   pgtype.Timestamp `json:"time_created"`
	Author        string           `json:"author"`
	UpvotesCount  pgtype.Int4      `json:"upvotes_count"`
	RedditUpvotes pgtype.Int4      `json:"reddit_upvotes"`
}

type AnswerUpvote struct {
	AnswerUid pgtype.UUID `json:"answer_uid"`
	Username  string      `json:"username"`
}

type Chamber struct {
	Uid             pgtype.UUID      `json:"uid"`
	Name            string           `json:"name"`
	Description     pgtype.Text      `json:"description"`
	CreatorUsername pgtype.Text      `json:"creator_username"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	ColorIndex      pgtype.Int4      `json:"color_index"`
}

type ChamberMember struct {
	ChamberUid pgtype.UUID      `json:"chamber_uid"`
	Username   string           `json:"username"`
	JoinedAt   pgtype.Timestamp `json:"joined_at"`
}

type Notification struct {
	Uid           pgtype.UUID      `json:"uid"`
	UserUsername  string           `json:"user_username"`
	ActorUsername pgtype.Text      `json:"actor_username"`
	Type          string           `json:"type"`
	ReferenceUid  pgtype.UUID      `json:"reference_uid"`
	IsRead        pgtype.Bool      `json:"is_read"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type Question struct {
	Uid               pgtype.UUID      `json:"uid"`
	TimeCreated       pgtype.Timestamp `json:"time_created"`
	Content           pgtype.Text      `json:"content"`
	Author            string           `json:"author"`
	ChamberUid        pgtype.UUID      `json:"chamber_uid"`
	UpvotesCount      pgtype.Int4      `json:"upvotes_count"`
	RedditUpvotes     pgtype.Int4      `json:"reddit_upvotes"`
	AcceptedAnswerUid pgtype.UUID      `json:"accepted_answer_uid"`
	PinnedAt          pgtype.Timestamp `json:"pinned_at"`
}

type QuestionUpvote struct {
	Username    string      `json:"username"`
	QuestionUid pgtype.UUID `json:"question_uid"`
}

type User struct {
	Username          string           `json:"username"`
	Password          pgtype.Text      `json:"password"`
	Email             string           `json:"email"`
	Bio               pgtype.Text      `json:"bio"`
	Avatar            pgtype.Text      `json:"avatar"`
	Answered          pgtype.Int4      `json:"answered"`
	Posted            pgtype.Int4      `json:"posted"`
	VerificationToken pgtype.Text      `json:"verification_token"`
	IsVerified        pgtype.Bool      `json:"is_verified"`
	Links             pgtype.Text      `json:"links"`
	ResetToken        pgtype.Text      `json:"reset_token"`
	ResetExpiry       pgtype.Timestamp `json:"reset_expiry"`
}
