// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChamberMember = `-- name: AddChamberMember :exec
INSERT INTO chamber_members (chamber_uid, username) 
VALUES ($1, $2)
`

type AddChamberMemberParams struct {
	ChamberUid pgtype.UUID `json:"chamber_uid"`
	Username   string      `json:"username"`
}

func (q *Queries) AddChamberMember(ctx context.Context, arg AddChamberMemberParams) error {
	_, err := q.db.Exec(ctx, addChamberMember, arg.ChamberUid, arg.Username)
	return err
}

const checkNotificationExists = `-- name: CheckNotificationExists :one
SELECT exists(
    SELECT 1 FROM notifications 
    WHERE type = $1 AND actor_username = $2 AND reference_uid = $3
)
`

type CheckNotificationExistsParams struct {
	Type          string      `json:"type"`
	ActorUsername pgtype.Text `json:"actor_username"`
	ReferenceUid  pgtype.UUID `json:"reference_uid"`
}

func (q *Queries) CheckNotificationExists(ctx context.Context, arg CheckNotificationExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkNotificationExists, arg.Type, arg.ActorUsername, arg.ReferenceUid)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkUsernameExists = `-- name: CheckUsernameExists :one
SELECT count(*) 
FROM users 
WHERE username = $1
`

func (q *Queries) CheckUsernameExists(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRow(ctx, checkUsernameExists, username)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnswerVote = `-- name: CreateAnswerVote :exec
INSERT INTO answer_upvotes (answer_uid, username) 
VALUES ($1, $2)
`

type CreateAnswerVoteParams struct {
	AnswerUid pgtype.UUID `json:"answer_uid"`
	Username  string      `json:"username"`
}

func (q *Queries) CreateAnswerVote(ctx context.Context, arg CreateAnswerVoteParams) error {
	_, err := q.db.Exec(ctx, createAnswerVote, arg.AnswerUid, arg.Username)
	return err
}

const createChamber = `-- name: CreateChamber :exec
INSERT INTO chambers (uid, name, description, creator_username, color_index) 
VALUES ($1, $2, $3, $4, $5)
`

type CreateChamberParams struct {
	Uid             pgtype.UUID `json:"uid"`
	Name            string      `json:"name"`
	Description     pgtype.Text `json:"description"`
	CreatorUsername pgtype.Text `json:"creator_username"`
	ColorIndex      pgtype.Int4 `json:"color_index"`
}

func (q *Queries) CreateChamber(ctx context.Context, arg CreateChamberParams) error {
	_, err := q.db.Exec(ctx, createChamber,
		arg.Uid,
		arg.Name,
		arg.Description,
		arg.CreatorUsername,
		arg.ColorIndex,
	)
	return err
}

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications (user_username, actor_username, type, reference_uid) 
VALUES ($1, $2, $3, $4)
`

type CreateNotificationParams struct {
	UserUsername  string      `json:"user_username"`
	ActorUsername pgtype.Text `json:"actor_username"`
	Type          string      `json:"type"`
	ReferenceUid  pgtype.UUID `json:"reference_uid"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.Exec(ctx, createNotification,
		arg.UserUsername,
		arg.ActorUsername,
		arg.Type,
		arg.ReferenceUid,
	)
	return err
}

const createQuestion = `-- name: CreateQuestion :exec
INSERT INTO questions (content, author, chamber_uid) 
VALUES ($1, $2, $3)
`

type CreateQuestionParams struct {
	Content    pgtype.Text `json:"content"`
	Author     string      `json:"author"`
	ChamberUid pgtype.UUID `json:"chamber_uid"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) error {
	_, err := q.db.Exec(ctx, createQuestion, arg.Content, arg.Author, arg.ChamberUid)
	return err
}

const createQuestionVote = `-- name: CreateQuestionVote :exec
INSERT INTO question_upvotes (username, question_uid) 
VALUES ($1, $2)
`

type CreateQuestionVoteParams struct {
	Username    string      `json:"username"`
	QuestionUid pgtype.UUID `json:"question_uid"`
}

func (q *Queries) CreateQuestionVote(ctx context.Context, arg CreateQuestionVoteParams) error {
	_, err := q.db.Exec(ctx, createQuestionVote, arg.Username, arg.QuestionUid)
	return err
}

const createReply = `-- name: CreateReply :exec
INSERT INTO answers (uid, content, question_uid, author, time_created) 
VALUES ($1, $2, $3, $4, $5)
`

type CreateReplyParams struct {
	Uid         pgtype.UUID      `json:"uid"`
	Content     string           `json:"content"`
	QuestionUid pgtype.UUID      `json:"question_uid"`
	Author      string           `json:"author"`
	TimeCreated pgtype.Timestamp `json:"time_created"`
}

func (q *Queries) CreateReply(ctx context.Context, arg CreateReplyParams) error {
	_, err := q.db.Exec(ctx, createReply,
		arg.Uid,
		arg.Content,
		arg.QuestionUid,
		arg.Author,
		arg.TimeCreated,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (username, email, password, verification_token, is_verified) 
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserParams struct {
	Username          string      `json:"username"`
	Email             string      `json:"email"`
	Password          pgtype.Text `json:"password"`
	VerificationToken pgtype.Text `json:"verification_token"`
	IsVerified        pgtype.Bool `json:"is_verified"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.VerificationToken,
		arg.IsVerified,
	)
	return err
}

const decrementAnswerUpvotes = `-- name: DecrementAnswerUpvotes :exec
UPDATE answers SET upvotes_count = upvotes_count - 1 
WHERE uid = $1
`

func (q *Queries) DecrementAnswerUpvotes(ctx context.Context, uid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, decrementAnswerUpvotes, uid)
	return err
}

const decrementQuestionUpvotes = `-- name: DecrementQuestionUpvotes :exec
UPDATE questions SET upvotes_count = upvotes_count - 1 
WHERE uid = $1
`

func (q *Queries) DecrementQuestionUpvotes(ctx context.Context, uid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, decrementQuestionUpvotes, uid)
	return err
}

const deleteAnswerVote = `-- name: DeleteAnswerVote :exec
DELETE FROM answer_upvotes 
WHERE username = $1 AND answer_uid = $2
`

type DeleteAnswerVoteParams struct {
	Username  string      `json:"username"`
	AnswerUid pgtype.UUID `json:"answer_uid"`
}

func (q *Queries) DeleteAnswerVote(ctx context.Context, arg DeleteAnswerVoteParams) error {
	_, err := q.db.Exec(ctx, deleteAnswerVote, arg.Username, arg.AnswerUid)
	return err
}

const deleteChamber = `-- name: DeleteChamber :exec
DELETE FROM chambers 
WHERE creator_username = $1 AND name = $2
`

type DeleteChamberParams struct {
	CreatorUsername pgtype.Text `json:"creator_username"`
	Name            string      `json:"name"`
}

func (q *Queries) DeleteChamber(ctx context.Context, arg DeleteChamberParams) error {
	_, err := q.db.Exec(ctx, deleteChamber, arg.CreatorUsername, arg.Name)
	return err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM questions 
WHERE uid = $1 AND author = $2
`

type DeleteQuestionParams struct {
	Uid    pgtype.UUID `json:"uid"`
	Author string      `json:"author"`
}

func (q *Queries) DeleteQuestion(ctx context.Context, arg DeleteQuestionParams) error {
	_, err := q.db.Exec(ctx, deleteQuestion, arg.Uid, arg.Author)
	return err
}

const deleteQuestionVote = `-- name: DeleteQuestionVote :exec
DELETE FROM question_upvotes 
WHERE username = $1 AND question_uid = $2
`

type DeleteQuestionVoteParams struct {
	Username    string      `json:"username"`
	QuestionUid pgtype.UUID `json:"question_uid"`
}

func (q *Queries) DeleteQuestionVote(ctx context.Context, arg DeleteQuestionVoteParams) error {
	_, err := q.db.Exec(ctx, deleteQuestionVote, arg.Username, arg.QuestionUid)
	return err
}

const deleteReply = `-- name: DeleteReply :exec
DELETE FROM answers 
WHERE uid = $1 AND question_uid = $2 AND author = $3
`

type DeleteReplyParams struct {
	Uid         pgtype.UUID `json:"uid"`
	QuestionUid pgtype.UUID `json:"question_uid"`
	Author      string      `json:"author"`
}

func (q *Queries) DeleteReply(ctx context.Context, arg DeleteReplyParams) error {
	_, err := q.db.Exec(ctx, deleteReply, arg.Uid, arg.QuestionUid, arg.Author)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users 
WHERE username = $1
`

func (q *Queries) DeleteUser(ctx context.Context, username string) error {
	_, err := q.db.Exec(ctx, deleteUser, username)
	return err
}

const getAnswerAuthor = `-- name: GetAnswerAuthor :one
SELECT author FROM answers WHERE uid = $1
`

func (q *Queries) GetAnswerAuthor(ctx context.Context, uid pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getAnswerAuthor, uid)
	var author string
	err := row.Scan(&author)
	return author, err
}

const getAnswerVote = `-- name: GetAnswerVote :one
SELECT answer_uid, username 
FROM answer_upvotes 
WHERE username = $1 AND answer_uid = $2
`

type GetAnswerVoteParams struct {
	Username  string      `json:"username"`
	AnswerUid pgtype.UUID `json:"answer_uid"`
}

func (q *Queries) GetAnswerVote(ctx context.Context, arg GetAnswerVoteParams) (AnswerUpvote, error) {
	row := q.db.QueryRow(ctx, getAnswerVote, arg.Username, arg.AnswerUid)
	var i AnswerUpvote
	err := row.Scan(&i.AnswerUid, &i.Username)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT
    u.username, u.email, COALESCE(u.bio, '') as bio, COALESCE(u.avatar, '') as avatar, COALESCE(u.links, '') as links,
    (SELECT COUNT(*) FROM questions q WHERE q.author = u.username) as posted,
    (SELECT COUNT(*) FROM answers a WHERE a.author = u.username) as answered
FROM users u
WHERE u.username = $1
`

type GetProfileRow struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Bio      string `json:"bio"`
	Avatar   string `json:"avatar"`
	Links    string `json:"links"`
	Posted   int64  `json:"posted"`
	Answered int64  `json:"answered"`
}

func (q *Queries) GetProfile(ctx context.Context, username string) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, username)
	var i GetProfileRow
	err := row.Scan(
		&i.Username,
		&i.Email,
		&i.Bio,
		&i.Avatar,
		&i.Links,
		&i.Posted,
		&i.Answered,
	)
	return i, err
}

const getPublicProfile = `-- name: GetPublicProfile :one
SELECT
    u.username, COALESCE(u.bio, '') as bio, COALESCE(u.avatar, '') as avatar, COALESCE(u.links, '') as links,
    (SELECT COUNT(*) FROM questions q WHERE q.author = u.username) as posted,
    (SELECT COUNT(*) FROM answers a WHERE a.author = u.username) as answered
FROM users u
WHERE u.username = $1
`

type GetPublicProfileRow struct {
	Username string `json:"username"`
	Bio      string `json:"bio"`
	Avatar   string `json:"avatar"`
	Links    string `json:"links"`
	Posted   int64  `json:"posted"`
	Answered int64  `json:"answered"`
}

func (q *Queries) GetPublicProfile(ctx context.Context, username string) (GetPublicProfileRow, error) {
	row := q.db.QueryRow(ctx, getPublicProfile, username)
	var i GetPublicProfileRow
	err := row.Scan(
		&i.Username,
		&i.Bio,
		&i.Avatar,
		&i.Links,
		&i.Posted,
		&i.Answered,
	)
	return i, err
}

const getQuestion = `-- name: GetQuestion :one
SELECT
    q.uid,
    q.content,
    q.time_created,
    q.author,
    u.avatar,
    q.upvotes_count as upvotes,
    exists (
        select 1 from question_upvotes v2
        where v2.question_uid = q.uid and v2.username = $1
    ) as is_upvoted
FROM questions q
LEFT JOIN users u on u.username = q.author
WHERE q.uid = $2
`

type GetQuestionParams struct {
	CurrentUser string      `json:"current_user"`
	Uid         pgtype.UUID `json:"uid"`
}

type GetQuestionRow struct {
	Uid         pgtype.UUID      `json:"uid"`
	Content     pgtype.Text      `json:"content"`
	TimeCreated pgtype.Timestamp `json:"time_created"`
	Author      string           `json:"author"`
	Avatar      pgtype.Text      `json:"avatar"`
	Upvotes     pgtype.Int4      `json:"upvotes"`
	IsUpvoted   bool             `json:"is_upvoted"`
}

func (q *Queries) GetQuestion(ctx context.Context, arg GetQuestionParams) (GetQuestionRow, error) {
	row := q.db.QueryRow(ctx, getQuestion, arg.CurrentUser, arg.Uid)
	var i GetQuestionRow
	err := row.Scan(
		&i.Uid,
		&i.Content,
		&i.TimeCreated,
		&i.Author,
		&i.Avatar,
		&i.Upvotes,
		&i.IsUpvoted,
	)
	return i, err
}

const getQuestionAuthor = `-- name: GetQuestionAuthor :one
SELECT author FROM questions WHERE uid = $1
`

func (q *Queries) GetQuestionAuthor(ctx context.Context, uid pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getQuestionAuthor, uid)
	var author string
	err := row.Scan(&author)
	return author, err
}

const getQuestionVote = `-- name: GetQuestionVote :one
SELECT username, question_uid 
FROM question_upvotes 
WHERE username = $1 AND question_uid = $2
`

type GetQuestionVoteParams struct {
	Username    string      `json:"username"`
	QuestionUid pgtype.UUID `json:"question_uid"`
}

func (q *Queries) GetQuestionVote(ctx context.Context, arg GetQuestionVoteParams) (QuestionUpvote, error) {
	row := q.db.QueryRow(ctx, getQuestionVote, arg.Username, arg.QuestionUid)
	var i QuestionUpvote
	err := row.Scan(&i.Username, &i.QuestionUid)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT username, is_verified 
FROM users 
WHERE email = $1
`

type GetUserByEmailRow struct {
	Username   string      `json:"username"`
	IsVerified pgtype.Bool `json:"is_verified"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(&i.Username, &i.IsVerified)
	return i, err
}

const getUserByResetToken = `-- name: GetUserByResetToken :one
SELECT email, reset_expiry 
FROM users 
WHERE reset_token = $1
`

type GetUserByResetTokenRow struct {
	Email       string           `json:"email"`
	ResetExpiry pgtype.Timestamp `json:"reset_expiry"`
}

func (q *Queries) GetUserByResetToken(ctx context.Context, resetToken pgtype.Text) (GetUserByResetTokenRow, error) {
	row := q.db.QueryRow(ctx, getUserByResetToken, resetToken)
	var i GetUserByResetTokenRow
	err := row.Scan(&i.Email, &i.ResetExpiry)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT username, email, password, is_verified 
FROM users 
WHERE username = $1
`

type GetUserByUsernameRow struct {
	Username   string      `json:"username"`
	Email      string      `json:"email"`
	Password   pgtype.Text `json:"password"`
	IsVerified pgtype.Bool `json:"is_verified"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.Username,
		&i.Email,
		&i.Password,
		&i.IsVerified,
	)
	return i, err
}

const incrementAnswerUpvotes = `-- name: IncrementAnswerUpvotes :exec
UPDATE answers SET upvotes_count = upvotes_count + 1 
WHERE uid = $1
`

func (q *Queries) IncrementAnswerUpvotes(ctx context.Context, uid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementAnswerUpvotes, uid)
	return err
}

const incrementQuestionUpvotes = `-- name: IncrementQuestionUpvotes :exec
UPDATE questions SET upvotes_count = upvotes_count + 1 
WHERE uid = $1
`

func (q *Queries) IncrementQuestionUpvotes(ctx context.Context, uid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementQuestionUpvotes, uid)
	return err
}

const joinChamber = `-- name: JoinChamber :exec
INSERT INTO chamber_members (chamber_uid, username) 
VALUES ($1, $2) 
ON CONFLICT DO NOTHING
`

type JoinChamberParams struct {
	ChamberUid pgtype.UUID `json:"chamber_uid"`
	Username   string      `json:"username"`
}

func (q *Queries) JoinChamber(ctx context.Context, arg JoinChamberParams) error {
	_, err := q.db.Exec(ctx, joinChamber, arg.ChamberUid, arg.Username)
	return err
}

const leaveChamber = `-- name: LeaveChamber :exec
DELETE FROM chamber_members 
WHERE chamber_uid = $1 AND username = $2
`

type LeaveChamberParams struct {
	ChamberUid pgtype.UUID `json:"chamber_uid"`
	Username   string      `json:"username"`
}

func (q *Queries) LeaveChamber(ctx context.Context, arg LeaveChamberParams) error {
	_, err := q.db.Exec(ctx, leaveChamber, arg.ChamberUid, arg.Username)
	return err
}

const listChambers = `-- name: ListChambers :many
SELECT 
    c.uid, 
    c.name, 
    COALESCE(c.description, '') as description, 
    c.color_index,
    c.created_at,
    (SELECT COUNT(*) FROM chamber_members cm WHERE cm.chamber_uid = c.uid) as member_count,
    EXISTS(SELECT 1 FROM chamber_members cm WHERE cm.chamber_uid = c.uid AND cm.username = $2) as is_joined
FROM chambers c
WHERE ($1::text IS NULL OR c.name ILIKE '%' || $1 || '%' OR c.description ILIKE '%' || $1 || '%')
`

type ListChambersParams struct {
	Column1     string `json:"column_1"`
	CurrentUser string `json:"current_user"`
}

type ListChambersRow struct {
	Uid         pgtype.UUID      `json:"uid"`
	Name        string           `json:"name"`
	Description string           `json:"description"`
	ColorIndex  pgtype.Int4      `json:"color_index"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	MemberCount int64            `json:"member_count"`
	IsJoined    bool             `json:"is_joined"`
}

func (q *Queries) ListChambers(ctx context.Context, arg ListChambersParams) ([]ListChambersRow, error) {
	rows, err := q.db.Query(ctx, listChambers, arg.Column1, arg.CurrentUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChambersRow
	for rows.Next() {
		var i ListChambersRow
		if err := rows.Scan(
			&i.Uid,
			&i.Name,
			&i.Description,
			&i.ColorIndex,
			&i.CreatedAt,
			&i.MemberCount,
			&i.IsJoined,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestions = `-- name: ListQuestions :many
SELECT
    q.uid,
    q.content,
    q.time_created,
    q.author,
    u.avatar,
    q.upvotes_count as upvotes,
    exists (
        select 1 from question_upvotes v2
        where v2.question_uid = q.uid and v2.username = $3
    ) as is_upvoted,
    q.chamber_uid,
    coalesce(c.name, '') as chamber_name
FROM questions q
LEFT JOIN users u ON u.username = q.author
LEFT JOIN chambers c ON c.uid = q.chamber_uid
ORDER BY q.time_created DESC
LIMIT $1 OFFSET $2
`

type ListQuestionsParams struct {
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
	CurrentUser string `json:"current_user"`
}

type ListQuestionsRow struct {
	Uid         pgtype.UUID      `json:"uid"`
	Content     pgtype.Text      `json:"content"`
	TimeCreated pgtype.Timestamp `json:"time_created"`
	Author      string           `json:"author"`
	Avatar      pgtype.Text      `json:"avatar"`
	Upvotes     pgtype.Int4      `json:"upvotes"`
	IsUpvoted   bool             `json:"is_upvoted"`
	ChamberUid  pgtype.UUID      `json:"chamber_uid"`
	ChamberName string           `json:"chamber_name"`
}

func (q *Queries) ListQuestions(ctx context.Context, arg ListQuestionsParams) ([]ListQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listQuestions, arg.Limit, arg.Offset, arg.CurrentUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuestionsRow
	for rows.Next() {
		var i ListQuestionsRow
		if err := rows.Scan(
			&i.Uid,
			&i.Content,
			&i.TimeCreated,
			&i.Author,
			&i.Avatar,
			&i.Upvotes,
			&i.IsUpvoted,
			&i.ChamberUid,
			&i.ChamberName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByAuthor = `-- name: ListQuestionsByAuthor :many
SELECT
    q.uid,
    q.content,
    q.time_created,
    q.author,
    u.avatar,
    q.upvotes_count as upvotes,
    exists (
        select 1 from question_upvotes v2
        where v2.question_uid = q.uid and v2.username = $3
    ) as is_upvoted,
    q.chamber_uid,
    coalesce(c.name, '') as chamber_name
FROM questions q
LEFT JOIN users u ON u.username = q.author
LEFT JOIN chambers c ON c.uid = q.chamber_uid
WHERE q.author = $4
ORDER BY q.time_created DESC
LIMIT $1 OFFSET $2
`

type ListQuestionsByAuthorParams struct {
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
	CurrentUser string `json:"current_user"`
	Author      string `json:"author"`
}

type ListQuestionsByAuthorRow struct {
	Uid         pgtype.UUID      `json:"uid"`
	Content     pgtype.Text      `json:"content"`
	TimeCreated pgtype.Timestamp `json:"time_created"`
	Author      string           `json:"author"`
	Avatar      pgtype.Text      `json:"avatar"`
	Upvotes     pgtype.Int4      `json:"upvotes"`
	IsUpvoted   bool             `json:"is_upvoted"`
	ChamberUid  pgtype.UUID      `json:"chamber_uid"`
	ChamberName string           `json:"chamber_name"`
}

func (q *Queries) ListQuestionsByAuthor(ctx context.Context, arg ListQuestionsByAuthorParams) ([]ListQuestionsByAuthorRow, error) {
	rows, err := q.db.Query(ctx, listQuestionsByAuthor,
		arg.Limit,
		arg.Offset,
		arg.CurrentUser,
		arg.Author,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuestionsByAuthorRow
	for rows.Next() {
		var i ListQuestionsByAuthorRow
		if err := rows.Scan(
			&i.Uid,
			&i.Content,
			&i.TimeCreated,
			&i.Author,
			&i.Avatar,
			&i.Upvotes,
			&i.IsUpvoted,
			&i.ChamberUid,
			&i.ChamberName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByChamber = `-- name: ListQuestionsByChamber :many
SELECT
    q.uid,
    q.content,
    q.time_created,
    q.author,
    u.avatar,
    q.upvotes_count as upvotes,
    exists (
        select 1 from question_upvotes v2
        where v2.question_uid = q.uid and v2.username = $3
    ) as is_upvoted,
    q.chamber_uid,
    coalesce(c.name, '') as chamber_name
FROM questions q
LEFT JOIN users u ON u.username = q.author
LEFT JOIN chambers c ON c.uid = q.chamber_uid
WHERE q.chamber_uid = $4
ORDER BY q.time_created DESC
LIMIT $1 OFFSET $2
`

type ListQuestionsByChamberParams struct {
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
	CurrentUser string      `json:"current_user"`
	ChamberUid  pgtype.UUID `json:"chamber_uid"`
}

type ListQuestionsByChamberRow struct {
	Uid         pgtype.UUID      `json:"uid"`
	Content     pgtype.Text      `json:"content"`
	TimeCreated pgtype.Timestamp `json:"time_created"`
	Author      string           `json:"author"`
	Avatar      pgtype.Text      `json:"avatar"`
	Upvotes     pgtype.Int4      `json:"upvotes"`
	IsUpvoted   bool             `json:"is_upvoted"`
	ChamberUid  pgtype.UUID      `json:"chamber_uid"`
	ChamberName string           `json:"chamber_name"`
}

func (q *Queries) ListQuestionsByChamber(ctx context.Context, arg ListQuestionsByChamberParams) ([]ListQuestionsByChamberRow, error) {
	rows, err := q.db.Query(ctx, listQuestionsByChamber,
		arg.Limit,
		arg.Offset,
		arg.CurrentUser,
		arg.ChamberUid,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuestionsByChamberRow
	for rows.Next() {
		var i ListQuestionsByChamberRow
		if err := rows.Scan(
			&i.Uid,
			&i.Content,
			&i.TimeCreated,
			&i.Author,
			&i.Avatar,
			&i.Upvotes,
			&i.IsUpvoted,
			&i.ChamberUid,
			&i.ChamberName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsTop = `-- name: ListQuestionsTop :many
SELECT
    q.uid,
    q.content,
    q.time_created,
    q.author,
    u.avatar,
    q.upvotes_count as upvotes,
    exists (
        select 1 from question_upvotes v2
        where v2.question_uid = q.uid and v2.username = $3
    ) as is_upvoted,
    q.chamber_uid,
    coalesce(c.name, '') as chamber_name
FROM questions q
LEFT JOIN users u ON u.username = q.author
LEFT JOIN chambers c ON c.uid = q.chamber_uid
ORDER BY q.upvotes_count DESC
LIMIT $1 OFFSET $2
`

type ListQuestionsTopParams struct {
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
	CurrentUser string `json:"current_user"`
}

type ListQuestionsTopRow struct {
	Uid         pgtype.UUID      `json:"uid"`
	Content     pgtype.Text      `json:"content"`
	TimeCreated pgtype.Timestamp `json:"time_created"`
	Author      string           `json:"author"`
	Avatar      pgtype.Text      `json:"avatar"`
	Upvotes     pgtype.Int4      `json:"upvotes"`
	IsUpvoted   bool             `json:"is_upvoted"`
	ChamberUid  pgtype.UUID      `json:"chamber_uid"`
	ChamberName string           `json:"chamber_name"`
}

func (q *Queries) ListQuestionsTop(ctx context.Context, arg ListQuestionsTopParams) ([]ListQuestionsTopRow, error) {
	rows, err := q.db.Query(ctx, listQuestionsTop, arg.Limit, arg.Offset, arg.CurrentUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuestionsTopRow
	for rows.Next() {
		var i ListQuestionsTopRow
		if err := rows.Scan(
			&i.Uid,
			&i.Content,
			&i.TimeCreated,
			&i.Author,
			&i.Avatar,
			&i.Upvotes,
			&i.IsUpvoted,
			&i.ChamberUid,
			&i.ChamberName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplies = `-- name: ListReplies :many
SELECT 
    a.uid,
    a.content,
    a.time_created,
    a.question_uid,
    a.author,
    u.avatar,
    a.upvotes_count as upvotes,
    exists (
        select 1 from answer_upvotes v2
        where v2.answer_uid = a.uid and v2.username = $2
    ) as is_upvoted
FROM answers a
LEFT JOIN users u ON u.username = a.author
WHERE a.question_uid = $1
LIMIT 200 OFFSET 0
`

type ListRepliesParams struct {
	QuestionUid pgtype.UUID `json:"question_uid"`
	CurrentUser string      `json:"current_user"`
}

type ListRepliesRow struct {
	Uid         pgtype.UUID      `json:"uid"`
	Content     string           `json:"content"`
	TimeCreated pgtype.Timestamp `json:"time_created"`
	QuestionUid pgtype.UUID      `json:"question_uid"`
	Author      string           `json:"author"`
	Avatar      pgtype.Text      `json:"avatar"`
	Upvotes     pgtype.Int4      `json:"upvotes"`
	IsUpvoted   bool             `json:"is_upvoted"`
}

func (q *Queries) ListReplies(ctx context.Context, arg ListRepliesParams) ([]ListRepliesRow, error) {
	rows, err := q.db.Query(ctx, listReplies, arg.QuestionUid, arg.CurrentUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepliesRow
	for rows.Next() {
		var i ListRepliesRow
		if err := rows.Scan(
			&i.Uid,
			&i.Content,
			&i.TimeCreated,
			&i.QuestionUid,
			&i.Author,
			&i.Avatar,
			&i.Upvotes,
			&i.IsUpvoted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchQuestions = `-- name: SearchQuestions :many
SELECT
    q.uid, q.content, q.time_created, q.author,
    u.avatar,
    q.upvotes_count,
    exists (select 1 from question_upvotes v2 where v2.question_uid = q.uid and v2.username = $3) as is_upvoted
FROM questions q
LEFT JOIN users u on u.username = q.author
WHERE q.content ilike $4
LIMIT $1 OFFSET $2
`

type SearchQuestionsParams struct {
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
	CurrentUser string      `json:"current_user"`
	Query       pgtype.Text `json:"query"`
}

type SearchQuestionsRow struct {
	Uid          pgtype.UUID      `json:"uid"`
	Content      pgtype.Text      `json:"content"`
	TimeCreated  pgtype.Timestamp `json:"time_created"`
	Author       string           `json:"author"`
	Avatar       pgtype.Text      `json:"avatar"`
	UpvotesCount pgtype.Int4      `json:"upvotes_count"`
	IsUpvoted    bool             `json:"is_upvoted"`
}

func (q *Queries) SearchQuestions(ctx context.Context, arg SearchQuestionsParams) ([]SearchQuestionsRow, error) {
	rows, err := q.db.Query(ctx, searchQuestions,
		arg.Limit,
		arg.Offset,
		arg.CurrentUser,
		arg.Query,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchQuestionsRow
	for rows.Next() {
		var i SearchQuestionsRow
		if err := rows.Scan(
			&i.Uid,
			&i.Content,
			&i.TimeCreated,
			&i.Author,
			&i.Avatar,
			&i.UpvotesCount,
			&i.IsUpvoted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPasswordResetToken = `-- name: SetPasswordResetToken :exec
UPDATE users SET reset_token = $1, reset_expiry = $2 
WHERE email = $3
`

type SetPasswordResetTokenParams struct {
	ResetToken  pgtype.Text      `json:"reset_token"`
	ResetExpiry pgtype.Timestamp `json:"reset_expiry"`
	Email       string           `json:"email"`
}

func (q *Queries) SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, setPasswordResetToken, arg.ResetToken, arg.ResetExpiry, arg.Email)
	return err
}

const setVerificationToken = `-- name: SetVerificationToken :exec
UPDATE users SET verification_token = $1 
WHERE email = $2
`

type SetVerificationTokenParams struct {
	VerificationToken pgtype.Text `json:"verification_token"`
	Email             string      `json:"email"`
}

func (q *Queries) SetVerificationToken(ctx context.Context, arg SetVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, setVerificationToken, arg.VerificationToken, arg.Email)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users SET password = $1, reset_token = NULL, reset_expiry = NULL 
WHERE email = $2
`

type UpdatePasswordParams struct {
	Password pgtype.Text `json:"password"`
	Email    string      `json:"email"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.Password, arg.Email)
	return err
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE questions SET content = $1 
WHERE uid = $2 AND author = $3 
RETURNING uid
`

type UpdateQuestionParams struct {
	Content pgtype.Text `json:"content"`
	Uid     pgtype.UUID `json:"uid"`
	Author  string      `json:"author"`
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateQuestion, arg.Content, arg.Uid, arg.Author)
	var uid pgtype.UUID
	err := row.Scan(&uid)
	return uid, err
}

const updateReply = `-- name: UpdateReply :one
UPDATE answers SET content = $1 
WHERE uid = $2 AND author = $3 
RETURNING uid
`

type UpdateReplyParams struct {
	Content string      `json:"content"`
	Uid     pgtype.UUID `json:"uid"`
	Author  string      `json:"author"`
}

func (q *Queries) UpdateReply(ctx context.Context, arg UpdateReplyParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateReply, arg.Content, arg.Uid, arg.Author)
	var uid pgtype.UUID
	err := row.Scan(&uid)
	return uid, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET bio = $1, avatar = $2, links = $3, username = $4 
WHERE username = $5
`

type UpdateUserParams struct {
	Bio        pgtype.Text `json:"bio"`
	Avatar     pgtype.Text `json:"avatar"`
	Links      pgtype.Text `json:"links"`
	Username   string      `json:"username"`
	Username_2 string      `json:"username_2"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Bio,
		arg.Avatar,
		arg.Links,
		arg.Username,
		arg.Username_2,
	)
	return err
}

const verifyUser = `-- name: VerifyUser :one
UPDATE users SET is_verified = TRUE, verification_token = NULL 
WHERE verification_token = $1 
RETURNING username
`

func (q *Queries) VerifyUser(ctx context.Context, verificationToken pgtype.Text) (string, error) {
	row := q.db.QueryRow(ctx, verifyUser, verificationToken)
	var username string
	err := row.Scan(&username)
	return username, err
}
