// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddChamberMember(ctx context.Context, arg AddChamberMemberParams) error
	CheckNotificationExists(ctx context.Context, arg CheckNotificationExistsParams) (bool, error)
	CheckUsernameExists(ctx context.Context, username string) (int64, error)
	CreateAnswerVote(ctx context.Context, arg CreateAnswerVoteParams) error
	CreateChamber(ctx context.Context, arg CreateChamberParams) error
	CreateNotification(ctx context.Context, arg CreateNotificationParams) error
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (pgtype.UUID, error)
	CreateQuestionVote(ctx context.Context, arg CreateQuestionVoteParams) error
	CreateReply(ctx context.Context, arg CreateReplyParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DecrementAnswerUpvotes(ctx context.Context, uid pgtype.UUID) error
	DecrementQuestionUpvotes(ctx context.Context, uid pgtype.UUID) error
	DeleteAnswerVote(ctx context.Context, arg DeleteAnswerVoteParams) error
	DeleteChamber(ctx context.Context, arg DeleteChamberParams) error
	DeleteQuestion(ctx context.Context, arg DeleteQuestionParams) error
	DeleteQuestionVote(ctx context.Context, arg DeleteQuestionVoteParams) error
	DeleteReply(ctx context.Context, arg DeleteReplyParams) error
	DeleteUser(ctx context.Context, username string) error
	GetAnswerAuthor(ctx context.Context, uid pgtype.UUID) (string, error)
	GetAnswerVote(ctx context.Context, arg GetAnswerVoteParams) (AnswerUpvote, error)
	GetChamberCreator(ctx context.Context, uid pgtype.UUID) (pgtype.Text, error)
	GetProfile(ctx context.Context, username string) (GetProfileRow, error)
	GetPublicProfile(ctx context.Context, username string) (GetPublicProfileRow, error)
	GetQuestion(ctx context.Context, arg GetQuestionParams) (GetQuestionRow, error)
	GetQuestionAuthor(ctx context.Context, uid pgtype.UUID) (string, error)
	GetQuestionVote(ctx context.Context, arg GetQuestionVoteParams) (QuestionUpvote, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByResetToken(ctx context.Context, resetToken pgtype.Text) (GetUserByResetTokenRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	IncrementAnswerUpvotes(ctx context.Context, uid pgtype.UUID) error
	IncrementQuestionUpvotes(ctx context.Context, uid pgtype.UUID) error
	JoinChamber(ctx context.Context, arg JoinChamberParams) error
	LeaveChamber(ctx context.Context, arg LeaveChamberParams) error
	ListChambers(ctx context.Context, arg ListChambersParams) ([]ListChambersRow, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error)
	ListQuestions(ctx context.Context, arg ListQuestionsParams) ([]ListQuestionsRow, error)
	ListQuestionsByAuthor(ctx context.Context, arg ListQuestionsByAuthorParams) ([]ListQuestionsByAuthorRow, error)
	ListQuestionsByChamber(ctx context.Context, arg ListQuestionsByChamberParams) ([]ListQuestionsByChamberRow, error)
	ListQuestionsFiltered(ctx context.Context, arg ListQuestionsFilteredParams) ([]ListQuestionsFilteredRow, error)
	ListQuestionsTop(ctx context.Context, arg ListQuestionsTopParams) ([]ListQuestionsTopRow, error)
	ListReplies(ctx context.Context, arg ListRepliesParams) ([]ListRepliesRow, error)
	SearchChambers(ctx context.Context, arg SearchChambersParams) ([]SearchChambersRow, error)
	SearchQuestions(ctx context.Context, arg SearchQuestionsParams) ([]SearchQuestionsRow, error)
	SearchReplies(ctx context.Context, arg SearchRepliesParams) ([]SearchRepliesRow, error)
	SearchUsers(ctx context.Context, query pgtype.Text) ([]SearchUsersRow, error)
	SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) error
	SetVerificationToken(ctx context.Context, arg SetVerificationTokenParams) error
	UpdateChamber(ctx context.Context, arg UpdateChamberParams) (pgtype.UUID, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (pgtype.UUID, error)
	UpdateReply(ctx context.Context, arg UpdateReplyParams) (pgtype.UUID, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	VerifyUser(ctx context.Context, verificationToken pgtype.Text) (string, error)
}

var _ Querier = (*Queries)(nil)
